# Generated by Django 6.0.3 on 2026-03-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("REVIEWING", "Reviewing"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                    ("SELECTED", "Selected"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPLIED",
                max_length=20,
            ),
        ),
    ]
