# Generated by Django 6.0.3 on 2026-03-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("CLOSED", "Closed"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
