# Generated by Django 6.0.3 on 2026-03-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
